"""first migration

Revision ID: c05b017098e0
Revises: 
Create Date: 2026-09-06 20:02:51.668968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import synapse_api.infrastructure.persistence.sqlalchemy.types


# revision identifiers, used by Alembic.
revision: str = 'c05b017098e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', synapse_api.infrastructure.persistence.sqlalchemy.types.DepartmentIDType(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='unique_department_name')
    )
    op.create_table('roles',
    sa.Column('id', synapse_api.infrastructure.persistence.sqlalchemy.types.RoleIDType(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.Column('department_id', synapse_api.infrastructure.persistence.sqlalchemy.types.DepartmentIDType(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name', name='unique_role_name')
    )
    op.create_table('users',
    sa.Column('id', synapse_api.infrastructure.persistence.sqlalchemy.types.UserIDType(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role_id', synapse_api.infrastructure.persistence.sqlalchemy.types.RoleIDType(), nullable=False),
    sa.Column('email', synapse_api.infrastructure.persistence.sqlalchemy.types.EmailIDType(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', name='unique_username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('departments')
    # ### end Alembic commands ###
